//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaGreenWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionId { get; set; }
        public int TransactionTypeId { get; set; }
        public System.DateTime CDate { get; set; }
        public int UserId { get; set; }
        public long RoundId { get; set; }
        public long BalanceChange { get; set; }
        public string ReferenceId { get; set; }
    
        public virtual Game_Round Game_Round { get; set; }
        public virtual Transaction_Types Transaction_Types { get; set; }
        public virtual User User { get; set; }
    }
}
