//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaGreenWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Game_Round = new HashSet<Game_Round>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public long Balance { get; set; }
        public string Currency { get; set; }
        public System.DateTime CDate { get; set; }
        public System.DateTime LastLogin { get; set; }
    
        public virtual ICollection<Game_Round> Game_Round { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
